name: apply-destroy-aws-instance

on:
  workflow_dispatch:
    inputs:
      Action:
        type: choice
        required: true
        description: "apply|destroy"
        options:
          - devl
      Environment:
        type: choice
        required: true
        description: "Environment Name"
        options:
          - devl

permissions:
  id-token: write
  contents: read

jobs:
  EC2Instance:
    name: apply-destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: terraform actions - ${{github.event.inputs.Action}}
        run: |
          terraform init -backend-config="bucket=${{secrets.AWS_BUCKET_NAME_TF}}" -backend-config="key=tfstate/${{secrets.AWS_BUCKET_KEY_TF}}-${{github.event.inputs.Environment}}.tfstate"
          terraform fmt
          terraform validate
          terraform plan -var-file='vars/${{github.event.inputs.Environment}}.tfvars'
          terraform ${{github.event.inputs.Action}} --auto-approve -var-file="vars/${{github.event.inputs.Environment}}.tfvars" 
